spring:
  application:
    name: g-52-shop
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}}/${DB_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true

  mail:
    username: elenakarsten.ait@gmail.com
    password: nvcuaulzbulmdzvy
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            protocols: TLSv1.2
            trust: smtp.gmail.com
key:
  access: PmeJIM3j25UnYkWVhLVSTN5pPJCp6MV9sDiwS78F3Pk=
  refresh: vkAHeVVdv32EOxWH0lZykAq4KiYeKYBPlL8Trz9bhxE=

messages:
  hello: Hello from Digital Ocean!!